#!/usr/bin/env python3
"""Generate _data/publications.yml from files/publications.bib.

Usage:  python3 tools/bib2yml.py

No dependencies. Handles the subset of BibTeX used for journal articles:
title, author, journal, volume, number, pages, year, doi.
Authors are converted from "Last, F. and Last, F." to "F. Last, F. Last".
Entries are written newest-first; the site groups them by year.
"""

import re
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BIB = ROOT / "files" / "publications.bib"
OUT = ROOT / "_data" / "publications.yml"

ACCENTS = {
    r"\\'a": "á", r"\\'e": "é", r"\\'i": "í", r"\\'o": "ó", r"\\'u": "ú",
    r'\\"a': "ä", r'\\"e': "ë", r'\\"i': "ï", r'\\"o': "ö", r'\\"u': "ü",
    r"\\~n": "ñ", r"\\'A": "Á", r"\\'E": "É", r"\\'O": "Ó", r'\\"O': "Ö",
    r'\\"U': "Ü", r"\\~N": "Ñ",
}


def clean(value):
    value = value.strip().strip(",").strip()
    for pattern, char in ACCENTS.items():
        value = re.sub(pattern, char, value)
    value = value.replace("{", "").replace("}", "")
    value = value.replace("--", "–")
    value = re.sub(r"\bbeta-", "β-", value)
    return re.sub(r"\s+", " ", value).strip()


def fmt_authors(raw):
    out = []
    for name in re.split(r"\s+and\s+", raw):
        name = name.strip()
        if "," in name:
            last, first = name.split(",", 1)
            out.append(f"{first.strip()} {last.strip()}".strip())
        else:
            out.append(name)
    return ", ".join(out)


def parse(text):
    entries = []
    for block in re.finditer(r"@\w+\s*\{(.*?)\n\}", text, re.S):
        body = block.group(1)
        fields = {}
        for m in re.finditer(r"(\w+)\s*=\s*\{(.*?)\}\s*,?\s*(?=\n\s*\w+\s*=|\Z)", body, re.S):
            fields[m.group(1).lower()] = clean(m.group(2))
        if "title" in fields:
            entries.append(fields)
    return entries


def volume_label(e):
    vol, num, pages = e.get("volume", ""), e.get("number", ""), e.get("pages", "")
    label = vol
    if num:
        label = f"{vol}({num})"
    if pages:
        label = f"{label}, {pages}" if label else pages
    return label


def yaml_escape(value):
    return value.replace('"', "'")


def main():
    if not BIB.exists():
        sys.exit(f"missing {BIB}")
    entries = parse(BIB.read_text(encoding="utf-8"))
    entries.sort(key=lambda e: int(e.get("year", 0)), reverse=True)

    lines = ["# Auto-generated by tools/bib2yml.py from files/publications.bib — do not edit by hand."]
    for e in entries:
        lines.append(f'- title: "{yaml_escape(clean(e["title"]))}"')
        lines.append(f'  authors: "{yaml_escape(fmt_authors(e.get("author", "")))}"')
        lines.append(f'  journal: "{yaml_escape(e.get("journal", ""))}"')
        lines.append(f'  volume: "{yaml_escape(volume_label(e))}"')
        lines.append(f'  year: {e.get("year", "")}')
        lines.append(f'  doi: "{e.get("doi", "")}"')
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(entries)} entries to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
